### ISSUE TITLE
TypeError: Cannot convert a Symbol value to a string for JSX fragments

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [FormidableLabs/enzyme-matchers#198]
Given this test code:

```typescript
import { shallow } from "enzyme";
import "jest-enzyme";

// Arrange
const component = () => <>
    <span />
</>;

// Act
const rendered = shallow(component);

// Assert
expect(rendered).toContainReact(<span />);
```

```
TypeError: Cannot convert a Symbol value to a string

      at Object.toContainReact (node_modules/enzyme-matchers/lib/assertions/toContainReact.js:38:27)
      at Object.singleWrapper (node_modules/enzyme-matchers/lib/utils/single.js:33:27)
      at Object.<anonymous> (node_modules/jest-enzyme/lib/index.js:40:86)
      at Object.throwingMatcher [as toContainReact] (node_modules/expect/build/index.js:215:24)
      ...
```

As with my other two issues, I'd be up for sending a PR, but it's been 3 months since those were filed and I still haven't gotten around to it.

**Comment by blainekasten** [comment]
@JoshuaKGoldberg This is a problem with Enzyme and Fragments. https://github.com/airbnb/enzyme/issues/1213

I'm going to close this as there is nothing we can do here.
